### PR TITLE
Travis build fix

### LINKED ISSUE #6: Fix Travis CI of this repo
Travis cannot build this project. Go fix those errors!

Hint: Fibo .cpp works on TurboC++

### PR DESCRIPTION
**Pull request by dhruvhacks**
fixes #6

### CODE REVIEW

**Comment by dhruvhacks** [comment]
@sidhyatikku PS review.

**Comment by dhruvhacks** [comment]
@sidhyatikku Please review. :slightly_smiling_face:

**Comment by dhruvhacks** [comment]
@sidhyatikku Is there any change required for this PR??

**Comment by sidhyatikku** [comment]
No thanks! Have fun contributing. 🏁

**Pull request merged**
